# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanboard',
            name='isback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanboard',
            name='remark',
            field=models.TextField(default=''),
        ),
    ]
