# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlbapp', '0002_auto_20171105_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backboard',
            name='backtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 17, 52, 50, 597316)),
        ),
    ]
